### ISSUE TITLE
用PC端VLC播放流报错

### ISSUE THREAD

**Issue by AlexQcs** [sszhangpengfei/AndroidShow#1]
: NAL units are not preceeded by 0x00000001
03-19 15:05:53.862 18362-18623/com.zpf.androidshow W/libEGL: [ANDROID_RECORDABLE] format: 1
03-19 15:05:53.873 18362-18704/com.zpf.androidshow W/System.err: java.net.SocketException: sendto failed: EINVAL (Invalid argument)
03-19 15:05:53.878 18362-18704/com.zpf.androidshow W/System.err:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:628)
03-19 15:05:53.879 18362-18623/com.zpf.androidshow I/[MALI][Gralloc]: [+]r_hnd(0x7f86f82e60), client(53), share_fd(73)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:597)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:185)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at java.net.DatagramSocket.send(DatagramSocket.java:305)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at com.zpf.androidshow.rtsp.RtpSocket.run(RtpSocket.java:272)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err: Caused by: android.system.ErrnoException: sendto failed: EINVAL (Invalid argument)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at libcore.io.Posix.sendto(Posix.java:212)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:595)
03-19 15:05:53.881 18362-18704/com.zpf.androidshow W/System.err: 	... 4 more

**Comment by sszhangpengfei** [comment]
请让手机和pc在同一个局域网，用笔记本和手机连同一个wifi来试，如果一个用网线手机连wifi，那么手机的数据可能发送不过去。因为rtsp走的tcp，所以没有问题，rtp走的udp，如果存在跨网段的问题，那么手机数据是发送不过去的

**Comment by liukaibaby** [comment]
连接失败:
VLC 无法连接到「172.17.100.15:8086」。
您的输入无法被打开:
VLC 无法打开 MRL「rtsp://172.17.100.15:8086」。详情请检查日志。
